### ISSUE TITLE
Create a LORA from a ckpt file?

### ISSUE THREAD

**Issue by cmatrix7777** [hako-mikan/sd-webui-supermerger#13]
Is it possible to do it with this extension? 
If so, could you please tell how exactly?

**Comment by hako-mikan** [comment]
You can do that in LoRA tab. Choice model A and B, press "make LoRA" button(set alpha = 1 and beta = 1). If you mean making LoRA with single ckpt file, choice same model for model A and B, and set alpha = 1 and beta = 0. You can get LoRA based on model A.

**Comment by cmatrix7777** [comment]
Thanks for your reply. I've tried it just like you said: same ckpt in a and b and set alpha = 1 and beta = 0. Nothing else. And when I click on the button "Make LoRA (alpha * A - beta * B)" I get a red error message:

![supermerger lora from ckpt error](https://user-images.githubusercontent.com/96496408/221375868-d09de755-7853-4d1c-83a7-47b79ff96732.PNG)

And back in automatic1111:
make LoRA start
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model333.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model333.ckpt
^C

Any ideas?

**Comment by hako-mikan** [comment]
It seems you are using Colab and the problem seems to be specific to that environment. I have tried to correct the areas that I think are related to the problem, but I am not able to test it, so please try using it.
It should correctly appear as follows.
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>

**Comment by cmatrix7777** [comment]
Yes, in colab. Something changed but still not working. 
Memory issue? Maybe if adjusted for low ram / add errors for debugging.


make LoRA start
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model333.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Downloading100% 1.71G/1.71G [00:51<00:00, 33.3MB/s]
loading text encoder: <All keys matched successfully>
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model333.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
^C

**Comment by hako-mikan** [comment]
It could also be a memory problem; you may need more than 16GB of memory. 
In your case, you are trying to create a LoRA from a single model, so I have changed the program to reduce the number of times the model is loaded. If it is a memory issue, it may work. 
Also, converting the model to fp16 might improve it.

**Comment by cmatrix7777** [comment]
The free tier of google colab is 12 gb, so it needs to work below that.
Are you familiar with kohya?
https://www.youtube.com/watch?v=70H03cv57-o
https://github.com/bmaltais/kohya_ss
They managed to build one using less than 7 gb. Something with those settings should work in the free tier.
Here is the configuration file for the low ram:
https://mega.nz/file/zFNjlJAL#uB2uTAvcqLohSUzYBgtuBcAMt4Jnclg6jVV5YE4s0F4

**Comment by hako-mikan** [comment]
Since the kohya-ss script is used, there is no replacement in memory usage.
However, since this script is running on web-ui, memory for web-ui is used separately.

Try the web-ui test mode.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings/8fc36525ce0000f708956130eb35c8ee7 f3bd66d

This is where you specify "--xformers" and so on. Here you can start web-ui with "--ui-debug-mode" to start web-ui with memory saving instead of not being able to generate images. Images cannot be generated, but merging can be performed. In this case, you cannot select a model just by starting up, so please press the refresh button.

In my environment, it saved 1GB of memory. Please use this script after update to use in test mode.
If you use the fp16 model, you should end up with about 8GB of memory consumption.

Also, if you are creating a LoRA from a single model, I would suggest that you set the value of alpha to about 0.1. Usually, LoRA is created from the difference of two models, but in the case of a single model, the LoRA created is too strong and does not produce a proper image.

**Comment by hako-mikan** [comment]
Since there are many people reporting this issue, I decided to discuss it elsewhere.
Discuss the rest here.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
