### ISSUE TITLE
cannot get lora made by ckpt

### ISSUE THREAD

**Issue by moosescap** [hako-mikan/sd-webui-supermerger#15]
just follow ur answer on another question:"You can do that in LoRA tab. Choice model A and B, press "make LoRA" button(set alpha = 1 and beta = 1). If you mean making LoRA with single ckpt file, choice same model for model A and B, and set alpha = 1 and beta = 0. You can get LoRA based on model A."

and it gives me this:

make LoRA start
loading SD model : /content/drive/MyDrive/stable-diffusion-webui/models/Stable-diffusion/DeathNote_v2.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>

then it just pauses without any progression ...is there anything else should I do ?
Thank u!

**Comment by ClashSAN** [comment]
I did successfully extract with two models. You may need diffusers installed, not sure if you have.

**Comment by moosescap** [comment]
> I did successfully extract with two models. You may need diffusers installed, not sure if you have.
> 
> 我成功地提取了两个型号。您可能需要安装扩散器，不确定是否已经安装。

it shows '[+] diffusers version 0.10.2 installed.' so I think that's not the problem

**Comment by hako-mikan** [comment]
It seems you are using Colab and the problem seems to be specific to that environment. I have tried to correct the areas that I think are related to the problem, but I am not able to test it, so please try using it.
It should correctly appear as follows.
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>

**Comment by hako-mikan** [comment]
May be insufficient memory; 16 GB or more may be required. 
Converting the model to fp16, it might work.

**Comment by hako-mikan** [comment]
Since there are many people reporting this issue, I decided to discuss it elsewhere.
Discuss the rest here.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
