### ISSUE TITLE
If I don't refresh, the Webui doesn't respond to my input.

### ISSUE THREAD

**Issue by toyxyz** [hako-mikan/sd-webui-supermerger#228]
Webui commit : 5ef669de080814067961f28357256e8fe27544f4

If I don't refresh, the webui doesn't respond to input. The UI looks fine, but it doesn't respond to input and the extension list is stuck with the Loading message as shown below. My guess is that there is a conflict with sd-webui-prompt-all-in-one. Disabling either of them should fix the problem. https://github.com/Physton/sd-webui-prompt-all-in-one

![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/8006000/fdb9e30e-43f2-4d59-b6ca-2e1066b48b71)
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/8006000/3c2773e1-7b03-4a2f-8154-85b8fa3a56b9)

**Comment by hako-mikan** [comment]
This issue seems to occur when the option to automatically launch the browser is enabled in the web UI. 
It is probably happening because the launch timing is too early. 
You can avoid this by launching the browser manually.

This issue seems to be occurring due to an update to the web UI (including Gradio update), so it likely is an issue with Gradio rather than being caused by the two extensions.

**Comment by mikheys** [comment]
I have a similar problem. Until you refresh the page, nothing works.
