### ISSUE TITLE
Questions: chaining merges, save to disk, merge indication, loaded models, sequential merge, info and help.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [hako-mikan/sd-webui-supermerger#28]
It looks like a great extension, but I don't understand a few things about it.
1. How do I chain merges? If I have models A, B, C on disk, and I want to merge A +w0.5 B, then merge the result with C like that: ((A +w0.5 B) +w0.25 C). Is there a way to do it? In the field for "Model A" I don't see the result from the first merge, A +w0.5 B.
2. After I made a merge in memory how do I save it to disk? Do I need to select something in "save settings" and make merge again?
3. When models are being merged, there is no indication in UI, only in the terminal. It is confusing whether the process is working or not, or am I missing it somewhere, where can you see it? 
4. Only the last merged model is loaded in memory and can be used for the generation, right? Can I store 2 merged models in memory, and merge them together, or switch between them for a generation? With 32/64GB RAM, can I store 3/4/5+ merged models in memory and work with them?
5. If I use txt2img after a merge, would it use the last merged model? It shows the old model in the model selection field, maybe it can have a red indication or something that it isn't being used?
6. What is "Sequential XY Merge", what it can be used for?
7. Fields/buttons have no information about what they are doing and the help page not explaining much. I'm not sure how new people are supposed to figure out what the extension can do at all.

**Comment by a-l-e-x-d-s-9** [comment]
3. I've noticed that sometimes there is an indication on the right when models are being merged, but it does not always appear.

**Comment by hako-mikan** [comment]
1: This can be achieved by using merge mode sum Twice. Intermediate merges are not output.

2: Yes. Models loaded for image generation are not suitable for storage and must be merged again. Please check "save model" and Merge.

3: Yes, Current model is loaded model. It is indeed difficult to understand. I have been thinking about this issue since the beginning, but it is a difficult problem.

4: Yes. Only one model loaded. There are currently no plans to stock multiple merge models. 

5: The merged model will be applied in any tab until you reload the model. img2img may behave differently.

6: Please read README.

7:What is the Fields button?　No such button should exist.

**Comment by hako-mikan** [comment]
This is a somewhat complicated issue. 
There are two types of merged models: one for image generation and one for storage. 
The one for image generation is in fp16 format, while the one for preservation is in the same format as the original model. 
The save version is larger and usually deleted after it is saved. 
If you assume the functionality you are looking for, the program will need to keep the save file somewhere else apart from the model for generating
Of course, I understand the demand for merging multiple models together, so I will consider implementing your suggestion.
