### ISSUE TITLE
RAM usage keeps increasing continuously when I use the XYZ Plot. 

### ISSUE THREAD

**Issue by Ketorami** [hako-mikan/sd-webui-supermerger#311]
RAM usage keeps increasing continuously when I use the XYZ Plot. I've noticed that the more I merge models in the XY Plot, the more RAM it consumes. Sometimes my computer freezes for a while due to high RAM usage.

There are instances where errors occur during the XY Plot or when I plot the XY graph for the second time after the first plot. These errors often indicate that there is insufficient memory or sometimes there is no specific error message, just a prompt saying 
`[ Press any key to continue... ]`

![4 (1)](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/91450a78-32e7-42da-a9ca-924d8d74f543)
![4 (2)](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/2638ed96-bddb-4030-b3bd-93e97a1f0955)
![4 (4)](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/72150c79-2519-4b14-ae8f-5a42a276beab)
![4 (8)](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/50c2116b-c9d4-4093-959b-69d0c96487b4)
![4 (9)](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/75975a2f-0856-417f-9e17-605d3cedab89)

This problem is similar to the 'Load settings from' button. If I click on it before performing XY Merge, the problem arises.

I also have another issue: the 'Unload Model' button is not functioning.

**Comment by nCoderGit** [comment]
Your VRAM is likely getting exhausted due to the high resolution with Hires.Fix (and/or batch size set too high).

The newer NVIDIA drivers have a feature called `CUDA - Sysmem Fallback Policy` which will start offloading to system RAM when VRAM reaches a certain threshold. It prevents out-of-memory crashes (at least until your RAM is also full), but system memory is awefully slow in comparison, like 10x and more. And all you see as a user is some heavy slowdown without any real indicator to tell you if the graphics driver is actually offloading at the moment.

I'd choose `Prefer No Sysmem Fallback` in NVIDIA's control panel (only for `[webui path]\venv\Scripts\python.exe`, or globally to disable fallback for all applications) to get an instant OOM because then you know what resolution and batch size your 8GB 2060 Super can actually handle.
However, keep in mind that this will put a hard 8GB limit to what models you can load, so if you get OOMs while training or using SDXL you might wanna enable it again.

**Comment by hako-mikan** [comment]
If the problem only occurs when using kohya.hiresfix, then it is not an issue with supermerger. This is because the function to generate images uses the Web-UI's feature, not SuperMerger's.
